all:Jerusat1.3
Jerusat1.3:   
	  gcc -O4 -DNO_TCL -DSAT2003 --static -DDEFAULT_4 -I./inc ./src/C4AisOps.c ./src/C4ConfClsDel.c ./src/C4NewCC.c ./src/C4AlgImpl.c ./src/C4FreeMemory.c \
      ./src/C4PQNew.c ./src/C4Aux.c ./src/C4IVStacks.c ./src/C4PrePushD1Block.c \
      ./src/C4BoxOp.c ./src/C4Imply.c ./src/C4Queue.c ./src/C4BuildInitCnf.c \
      ./src/C4Layers.c ./src/C4Stack.c ./src/C4ConfActions.c ./src/C4MainSat2003.c -oJerusat1.3
