/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux DESKTOP-C7ASNEH 3.4.0+ x86_64"
#define LGL_COMPILED "Sat Mar 18 13:44:28 STD 2017"
#define LGL_RELEASED "Mon Nov  9 11:04:59 CET 2015"
#define LGL_VERSION "bal"
#define LGL_ID "2293bef0a4bd680210f6f5a453efa8b0a26f53ee"
